name: Generate Snake and Update Experience

on:
  schedule:
    - cron: "0 0 * * *"  # run daily at midnight UTC

  workflow_dispatch:  # manual trigger

  push:
    branches:
      - master

jobs:
  generate_snake_and_experience:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Generate the snake SVGs
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. Calculate experience (years and months)
      - name: Calculate experience (years and months)
        id: experience
        run: |
          START_DATE="2022-01-01"
          TODAY=$(date +%Y-%m-%d)
          
          YEARS=$(($(date +%Y) - $(date -d "$START_DATE" +%Y)))
          MONTHS=$(($(date +%m) - $(date -d "$START_DATE" +%m)))

          if [ "$MONTHS" -lt 0 ]; then
            YEARS=$((YEARS - 1))
            MONTHS=$((MONTHS + 12))
          fi

          echo "years=${YEARS}" >> $GITHUB_OUTPUT
          echo "months=${MONTHS}" >> $GITHUB_OUTPUT

      # 4. Update README.md experience badge
      - name: Replace experience in README.md
        run: |
          sed -i -E "s|(https://img\.shields\.io/badge/Experience-)[0-9]+_years,_*[0-9]*_months|\1${{ steps.experience.outputs.years }}_years,_${{ steps.experience.outputs.months }}_months|" README.md

      # 5. Commit README and SVGs
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md dist/
          git commit -m "Update experience and snake animation" || echo "No changes to commit"
          git push

      # 6. Push SVGs to `output` branch
      - name: Push snake SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
